{% set name = "libtike-cufft" %}
{% set version = "0.8.0" %}
{% set build = 0 %}


# Set CUDA related variables
{% if linux64 and cuda_compiler_version != "None" %}
{% set cuda_build_prefix = "cuda" + cuda_compiler_version|string %}
{% else %}
{% set cuda_build_prefix = "" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/carterbox/ptychocg/archive/{{ version }}.tar.gz
  sha256: 4b5736468ec376e0540b0d4c69358490ed1f915f4a372e6b4c4555d6d8f21af6

build:
  number: {{ build }}
  string: {{ cuda_build_prefix }}py{{ py }}h{{ PKG_HASH }}_{{ build }}
  skip: true  # [py<35 or not (linux64 and cuda_compiler_version != 'None')]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --no-index --no-cache-dir --install-option="-GNinja"
  missing_dso_whitelist:
    - '*/libcuda.*'

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - swig
  host:
    - pip
    - python
    - scikit-build
    - setuptools_scm_git_archive
  run:
    - cupy
    - python

test:
  imports:
    - libtike

about:
  home: https://github.com/math-vrn/libtike-cufft
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    libtike-cufft provides a cuFFT implementation of core operators for Tike.
  doc_url: https://tike.readthedocs.io/
  dev_url: https://github.com/math-vrn/libtike-cufft

extra:
  recipe-maintainers:
    - carterbox
